### ISSUE TITLE
After updating from  v1.10.9 to v2.3.2 can't add anything to cart

### ISSUE THREAD

**Issue by Tomi1444** [PrestaShopCorp/ps_eventbus#186]
After update I can't add antything to cart. Button not working.
I have error 500 in console

![image](https://github.com/PrestaShopCorp/ps_eventbus/assets/118079647/cb03d100-bc55-4868-af75-7dd392db5c29)

**Comment by Tomi1444** [comment]
In Logs i have this messages:

```
[2023-09-10 19:13:12] ps_accounts.DEBUG: PrestaShop\Module\PsAccounts\Exception\RefreshTokenException: Unable to refresh user token : 422 The given data was invalid. in /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Repository/AbstractTokenRepository.php:180 Stack trace: #0 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Repository/AbstractTokenRepository.php(113): PrestaShop\Module\PsAccounts\Repository\AbstractTokenRepository->refreshToken('APJWN8eShAWfg4L...', NULL) #1 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Service/ShopLinkAccountService.php(150): PrestaShop\Module\PsAccounts\Repository\AbstractTokenRepository->getOrRefreshToken() #2 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Provider/ShopProvider.php(107): PrestaShop\Module\PsAccounts\Service\ShopLinkAccountService->isAccountLinkedV4() #3 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Provider/ShopProvider.php(149): PrestaShop\Module\PsAccounts\Provider\ShopProvider->formatShopData(Array, 'ps_metrics') #4 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Provider/ShopProvider.php(181): PrestaShop\Module\PsAccounts\Provider\ShopProvider->getShopsTree('ps_metrics') #5 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Presenter/PsAccountsPresenter.php(107): PrestaShop\Module\PsAccounts\Provider\ShopProvider->getUnlinkedShops('ps_metrics', 1) #6 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_metrics/ps_metrics.php(489): PrestaShop\Module\PsAccounts\Presenter\PsAccountsPresenter->present('ps_metrics') #7 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_metrics/src/Controller/Admin/MetricsController.php(126): Ps_metrics->loadPsAccountsAssets() #8 /home/sklepvid/domains/vidos-domofony.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): PrestaShop\Module\Ps_metrics\Controller\Admin\MetricsController->renderApp() #9 /home/sklepvid/domains/vidos-domofony.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /home/sklepvid/domains/vidos-domofony.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, false) #11 /home/sklepvid/domains/vidos-domofony.pl/public_html/admin123/index.php(82): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, false) #12 {main} [] []
[2023-09-10 19:13:12] ps_accounts.DEBUG: PrestaShop\Module\PsAccounts\Exception\RefreshTokenException: Unable to refresh user token : 422 The given data was invalid. in /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Repository/AbstractTokenRepository.php:180 Stack trace: #0 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Repository/AbstractTokenRepository.php(113): PrestaShop\Module\PsAccounts\Repository\AbstractTokenRepository->refreshToken('APJWN8eShAWfg4L...', NULL) #1 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Service/ShopLinkAccountService.php(150): PrestaShop\Module\PsAccounts\Repository\AbstractTokenRepository->getOrRefreshToken() #2 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Provider/ShopProvider.php(107): PrestaShop\Module\PsAccounts\Service\ShopLinkAccountService->isAccountLinkedV4() #3 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Provider/ShopProvider.php(126): PrestaShop\Module\PsAccounts\Provider\ShopProvider->formatShopData(Array, 'ps_metrics') #4 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Provider/ShopProvider.php(200): PrestaShop\Module\PsAccounts\Provider\ShopProvider->getCurrentShop('ps_metrics') #5 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Presenter/PsAccountsPresenter.php(107): PrestaShop\Module\PsAccounts\Provider\ShopProvider->getUnlinkedShops('ps_metrics', 1) #6 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_metrics/ps_metrics.php(489): PrestaShop\Module\PsAccounts\Presenter\PsAccountsPresenter->present('ps_metrics') #7 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_metrics/src/Controller/Admin/MetricsController.php(126): Ps_metrics->loadPsAccountsAssets() #8 /home/sklepvid/domains/vidos-domofony.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): PrestaShop\Module\Ps_metrics\Controller\Admin\MetricsController->renderApp() #9 /home/sklepvid/domains/vidos-domofony.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /home/sklepvid/domains/vidos-domofony.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, false) #11 /home/sklepvid/domains/vidos-domofony.pl/public_html/admin123/index.php(82): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, false) #12 {main} [] []
[2023-09-10 19:13:13] ps_accounts.DEBUG: PrestaShop\Module\PsAccounts\Exception\RefreshTokenException: Unable to refresh user token : 422 The given data was invalid. in /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Repository/AbstractTokenRepository.php:180 Stack trace: #0 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Repository/AbstractTokenRepository.php(113): PrestaShop\Module\PsAccounts\Repository\AbstractTokenRepository->refreshToken('APJWN8eShAWfg4L...', NULL) #1 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Service/ShopLinkAccountService.php(150): PrestaShop\Module\PsAccounts\Repository\AbstractTokenRepository->getOrRefreshToken() #2 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Provider/ShopProvider.php(107): PrestaShop\Module\PsAccounts\Service\ShopLinkAccountService->isAccountLinkedV4() #3 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Provider/ShopProvider.php(126): PrestaShop\Module\PsAccounts\Provider\ShopProvider->formatShopData(Array, 'ps_metrics') #4 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_accounts/classes/Presenter/PsAccountsPresenter.php(153): PrestaShop\Module\PsAccounts\Provider\ShopProvider->getCurrentShop('ps_metrics') #5 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_metrics/ps_metrics.php(489): PrestaShop\Module\PsAccounts\Presenter\PsAccountsPresenter->present('ps_metrics') #6 /home/sklepvid/domains/vidos-domofony.pl/public_html/modules/ps_metrics/src/Controller/Admin/MetricsController.php(126): Ps_metrics->loadPsAccountsAssets() #7 /home/sklepvid/domains/vidos-domofony.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): PrestaShop\Module\Ps_metrics\Controller\Admin\MetricsController->renderApp() #8 /home/sklepvid/domains/vidos-domofony.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /home/sklepvid/domains/vidos-domofony.pl/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, false) #10 /home/sklepvid/domains/vidos-domofony.pl/public_html/admin123/index.php(82): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, false) #11 {main} [] []

```

**Comment by jokesterfr** [comment]
Thank you for your report.
We are aware of an issue in the carts sync process, when the store has a lot of cart rules this may cause an OOM issue during PHP execution. This issue will be soon addressed.

Upgrades of modules are often incertain, due to how module management is handled in PrestaShop. For instance, removed files are kept within the module folder during Upgrade.

In the meantime of our upcoming fix, could you delete the module completely from disk, and reinstall it (version 2.3.4)?

Sorry for the inconvenience and the response time to the ticket, we will soon enhance our tracking system to notify the team earlier.

**Comment by fox-john** [comment]
@Tomi1444 This issue has not been answered for a very long time. Since then, several versions of Ps_Eventbus have been released. We invite you to update your module and see if the problem persists.

If this is the case, we invite you to contact us again, either here or via support directly.

In the meantime, I am closing the ticket for prolonged inactivity.
